// Fictional demo content. These records do not represent live store operations.
export const stores = [
  { id: 'bankstown', name: 'Bankstown', state: 'NSW', area: 'South-west Sydney', status: 'attention', orders: 186, readiness: 82, team: 14 },
  { id: 'granville', name: 'Granville', state: 'NSW', area: 'Western Sydney', status: 'steady', orders: 164, readiness: 100, team: 12 },
  { id: 'punchbowl', name: 'Punchbowl', state: 'NSW', area: 'South-west Sydney', status: 'steady', orders: 142, readiness: 96, team: 11 },
  { id: 'ivanhoe', name: 'Ivanhoe', state: 'VIC', area: 'Melbourne', status: 'steady', orders: 118, readiness: 100, team: 10 },
];

export const stages = [
  {
    id: 'opening',
    label: 'Open the doors',
    time: '09:30',
    eyebrow: 'A good shift starts here',
    title: 'The whole store, ready together.',
    description: 'The opening checklist finds the team in their store channel. Everyone can read the Store Hub, then run the approved workflow to record their part.',
    zone: 'counter',
    signal: 'Four opening checks to work through together.',
    source: 'Store Hub · opening workflow',
    metric: { value: '0 / 4', label: 'opening checks complete', baseline: 'Four checks before opening' },
    steps: [
      { label: 'See the shift', detail: 'Read today’s roles, current promotion and manager contact in the Store Hub.' },
      { label: 'Finish the checks', detail: 'Use the approved opening workflow to confirm the counter and collection area are ready.' },
      { label: 'Let everyone know', detail: 'The workflow posts the result once, with the person responsible and the time.' },
    ],
    messages: [
      { name: 'Store OS', role: 'Approved app', initials: 'OS', text: 'Morning, team. Four opening checks are ready. Run the opening workflow to record each one.' },
      { name: 'Layla Darwish', role: 'Shift leader', initials: 'LA', text: 'I’ve got the counter. Omar, could you check the collection area? Today’s promotion is in the Store Hub.' },
      { name: 'Omar Haddad', role: 'Team member', initials: 'OM', text: 'On it. I’ll record it in the opening workflow so the next person can see it’s done.' },
    ],
    actions: [
      { id: 'opening-complete', label: 'Finish opening checks', kind: 'primary', result: 'All four opening checks are complete. The store is ready to open, with the result visible to the team.' },
      { id: 'opening-view-hub', label: 'Read the Store Hub', kind: 'secondary', result: 'The Store Hub brings together today’s promotion, opening checklist, training links and manager contact. Team members can read it and run the approved checklist workflow.' },
    ],
    outcome: 'The doors open with the whole team on the same page.',
  },
  {
    id: 'prep',
    label: 'Get the prep right',
    time: '11:15',
    eyebrow: 'Care before the rush',
    title: 'Keep the checks close to the coals.',
    description: 'A quiet reminder brings the right food safety check to the shift leader. The approved record stays in the food safety system, with its status visible in Slack.',
    zone: 'grill',
    signal: 'The pre-service food safety record is awaiting review.',
    source: 'Food safety app · approved workflow',
    metric: { value: '1', label: 'check awaiting review', baseline: 'Follow the store’s approved procedure' },
    steps: [
      { label: 'Bring up the right check', detail: 'Open the approved food safety workflow from the store channel.' },
      { label: 'Follow the procedure', detail: 'The responsible team member follows the current store procedure and records the check in the source system.' },
      { label: 'Confirm the outcome', detail: 'The shift leader reviews the record. Slack receives the status and a link, with no duplicate record.' },
    ],
    messages: [
      { name: 'Store OS', role: 'Approved app', initials: 'OS', text: 'Layla, the pre-service food safety record is ready for your review. The current procedure is linked in the Store Hub.' },
      { name: 'Omar Haddad', role: 'Team member', initials: 'OM', text: 'The check is recorded in the food safety app. I’ve added a note for you to review before service.' },
      { name: 'Layla Darwish', role: 'Shift leader', initials: 'LA', text: 'Thanks. I’ll review the record there and confirm the status here.' },
    ],
    actions: [
      { id: 'prep-review-check', label: 'Complete review', kind: 'primary', result: 'The food safety record is marked reviewed. The store channel now shows the owner, status and a link to the original record.' },
      { id: 'prep-view-procedure', label: 'See the hand-off', kind: 'secondary', result: 'Slack links the team to the approved food safety procedure and original record. The responsible person carries out the check in that system, then the workflow returns its status to the channel.' },
    ],
    outcome: 'The team can see the check is done and where the record lives.',
  },
  {
    id: 'rush',
    label: 'Handle the rush',
    time: '18:42',
    eyebrow: 'A clear next move',
    title: 'Catch the queue while it still counts.',
    description: 'A drive-thru signal turns into a short, useful message. The shift leader sees what changed, takes ownership and acts while dinner is still on.',
    zone: 'counter',
    signal: 'Drive-thru pace is above this store’s usual range.',
    source: 'Fingermark · store baseline',
    metric: { value: '5:48', label: 'average ticket time', baseline: 'Store target 4:10 · rolling 30 minutes' },
    steps: [
      { label: 'Spot the change', detail: 'The drive-thru feed shows car count 22% above a normal Tuesday, with ticket time at 5:48.' },
      { label: 'Give it an owner', detail: 'Sarah takes the alert. The suggested response is to open the second window and move one packer to assembly.' },
      { label: 'Check the next window', detail: 'A follow-up records whether the change helped. The area manager only receives an escalation if the issue remains open.' },
    ],
    messages: [
      { name: 'Store OS', role: 'Approved app', initials: 'OS', text: 'Drive-thru ticket time is 5:48 against this store’s 4:10 target. Car count is 22% above a normal Tuesday. Suggested action: open the second window and move one packer to assembly.' },
      { name: 'Layla Darwish', role: 'Shift leader', initials: 'LA', text: 'I’ll take this. Omar is moving to assembly and I’m opening the second window.' },
      { name: 'Karim Nasser', role: 'Area manager', initials: 'KA', text: 'The owner and plan are visible here. Escalate to me if the next check is still above the store’s range.' },
    ],
    actions: [
      { id: 'rush-run-playbook', label: 'Run the rush playbook', kind: 'primary', result: 'Sarah owns the alert. The second window is open, a packer has moved to assembly and the follow-up shows the queue easing.' },
      { id: 'rush-inspect-signal', label: 'Compare the signal', kind: 'secondary', result: 'The current rolling average is 5:48. The same window last week was 4:05, with today’s car count 22% higher than a normal Tuesday. Review the next window with the shift leader.' },
    ],
    outcome: 'A faster handover, a calmer queue and a visible decision.',
  },
  {
    id: 'supply',
    label: 'Keep orders moving',
    time: '19:05',
    eyebrow: 'Stock meets service',
    title: 'Bring delivery back to the table.',
    description: 'A paused delivery feed reaches the store manager with the next step attached. The team checks availability, confirms the change and keeps the decision in the channel.',
    zone: 'stock',
    signal: 'Uber Eats is paused during trading.',
    source: 'Delivery feed · stock workflow',
    metric: { value: '12 min', label: 'delivery feed paused', baseline: 'Incident during dinner service' },
    steps: [
      { label: 'Notice the pause', detail: 'The delivery feed reports a pause while the store is trading.' },
      { label: 'Check what is available', detail: 'The stock workflow asks the shift leader to confirm that chicken packs and garlic sauce are ready for delivery orders.' },
      { label: 'Resume with an owner', detail: 'The manager confirms the availability check, then the delivery connection returns to online.' },
    ],
    messages: [
      { name: 'Store OS', role: 'Approved app', initials: 'OS', text: 'Uber Eats has been paused for 12 minutes. Sarah, please confirm stock and kitchen readiness before resuming delivery orders.' },
      { name: 'Layla Darwish', role: 'Shift leader', initials: 'LA', text: 'Chicken packs and garlic sauce are available. The packing bench is ready for delivery orders again.' },
      { name: 'Sarah Mansour', role: 'Store manager', initials: 'SA', text: 'Thanks. I’ll confirm the check and resume the delivery feed. The availability note can stay attached to this alert.' },
    ],
    actions: [
      { id: 'supply-resume-delivery', label: 'Confirm stock and resume', kind: 'primary', result: 'The delivery feed is back online. The availability check and manager decision are recorded against the alert.' },
      { id: 'supply-check-availability', label: 'Inspect availability', kind: 'secondary', result: 'The stock workflow shows chicken packs and garlic sauce available, with the packing bench ready. A manager still needs to confirm the decision to resume delivery.' },
    ],
    outcome: 'Orders can flow again, with the reason and owner easy to find.',
  },
  {
    id: 'people',
    label: 'Back the team',
    time: '19:20',
    eyebrow: 'The right help, in one place',
    title: 'Fill the gap without the phone chase.',
    description: 'A team member runs an approved cover request from the store channel. The connected workforce app handles availability and approval, then returns the outcome to Slack.',
    zone: 'crew',
    signal: 'One packing role needs cover for the late shift.',
    source: 'Workforce app · approved cover workflow',
    metric: { value: '1', label: 'late-shift role to cover', baseline: 'Manager approval in the workforce app' },
    steps: [
      { label: 'Ask once', detail: 'The shift leader runs the approved cover workflow from the store channel.' },
      { label: 'Match and approve', detail: 'The workforce app checks availability. A manager reviews the proposed cover there.' },
      { label: 'Tell the shift', detail: 'The approved outcome returns to Slack. The roster record remains in the workforce system.' },
    ],
    messages: [
      { name: 'Layla Darwish', role: 'Shift leader', initials: 'LA', text: 'We need one person on packing for the late shift. I’ve started the cover request from our channel.' },
      { name: 'Workforce app', role: 'Approved integration', initials: 'WF', text: 'A cover option is ready. Sarah can review the request and approve the roster change in the workforce app.' },
      { name: 'Sarah Mansour', role: 'Store manager', initials: 'SA', text: 'I’ll review it there. Once it’s approved, the team will get the outcome here without a second round of messages.' },
    ],
    actions: [
      { id: 'people-confirm-cover', label: 'Approve shift cover', kind: 'primary', result: 'The cover request is approved in the workforce app. Slack shows the outcome, and the roster remains in its original system.' },
      { id: 'people-see-workflow', label: 'See the cover workflow', kind: 'secondary', result: 'Team members run an existing approved workflow. The workforce app manages availability and the roster, a manager approves the change, and Slack brings the outcome back to the shift.' },
    ],
    outcome: 'The shift has cover and the team knows who is doing what.',
  },
  {
    id: 'close',
    label: 'Leave a good handover',
    time: '22:15',
    eyebrow: 'Tomorrow starts tonight',
    title: 'Finish the shift. Keep the knowledge.',
    description: 'The closing workflow gathers the shift’s decisions and outstanding work into a short recap. The morning crew starts with context, owners and a clear next step.',
    zone: 'dining',
    signal: 'The nightly recap is ready to review.',
    source: 'Closing workflow · channel history',
    metric: { value: '1', label: 'item for the morning crew', baseline: 'Check tomorrow’s packaging delivery' },
    steps: [
      { label: 'Record the handover', detail: 'The shift leader submits closing checks and an outstanding delivery note using the approved workflow.' },
      { label: 'Bring the story together', detail: 'The recap includes only workflow outcomes recorded in this shift. Unfinished work stays open.' },
      { label: 'Set up the next shift', detail: 'The packaging delivery follow-up has an owner and appears in the morning briefing.' },
    ],
    messages: [
      { name: 'Layla Darwish', role: 'Shift leader', initials: 'LA', text: 'Closing checks are recorded. One thing for the morning crew: please confirm the packaging delivery before lunch prep.' },
      { name: 'Store OS', role: 'Approved app', initials: 'OS', text: 'The draft recap will include recorded outcomes from this shift. Packaging delivery remains with Sarah for tomorrow.' },
      { name: 'Sarah Mansour', role: 'Store manager', initials: 'SA', text: 'That gives the morning crew what they need. I’ll take the packaging follow-up.' },
    ],
    actions: [
      { id: 'close-publish-recap', label: 'Post the recap', kind: 'primary', result: 'The nightly recap is posted in the store channel. Sarah owns the packaging follow-up and the morning crew can read the shift’s decisions in one place.' },
      { id: 'close-review-handover', label: 'Read the handover', kind: 'secondary', result: 'The handover covers recorded outcomes and carries forward the packaging delivery check, assigned to Sarah.' },
    ],
    outcome: 'The next shift starts in the know.',
  },
  {
    id: 'network',
    label: 'See the whole network',
    time: 'MON 07:00',
    eyebrow: 'From one store to every store',
    title: 'A Monday briefing with somewhere to go.',
    description: 'Area managers receive a concise store pack with the week’s focus and unfinished actions. They can drill into a store or ask an approved in-channel app a question about store data.',
    zone: 'roof',
    signal: 'The weekly store pack has arrived.',
    source: 'Snowflake store data · approved diagnostics app',
    metric: { value: '4', label: 'connected stores', baseline: 'Monday briefing with last week’s follow-ups' },
    steps: [
      { label: 'Start with the exceptions', detail: 'The store pack highlights each store’s focus metrics and carries forward unfinished actions.' },
      { label: 'Ask what is behind it', detail: 'The manager asks why Bankstown is down. The diagnostics app connects sales, delivery and guest experience signals.' },
      { label: 'Put the action near the team', detail: 'The manager assigns the next step in the relevant store channel with the evidence attached.' },
    ],
    messages: [
      { name: 'Store OS', role: 'Approved app', initials: 'OS', text: 'Morning, Karim. Your weekly pack is ready. Bankstown’s delivery performance needs a closer look. Last week’s outstanding actions are included.' },
      { name: 'Karim Nasser', role: 'Area manager', initials: 'KA', text: 'Why is Bankstown down this week?' },
      { name: 'Claude', role: 'Approved diagnostics app', initials: 'CL', text: 'Net sales are down 6.4% week on week. Uber Eats orders fell 19% while in-store transactions were flat. Delivery was paused for 84 minutes on Saturday and the rating moved from 4.6 to 4.4. Start with availability and packing checks.' },
    ],
    actions: [
      { id: 'network-assign-focus', label: 'Assign Bankstown’s focus', kind: 'primary', result: 'Bankstown’s store focus is assigned to Sarah: review delivery availability and packing checks. The evidence and follow-up stay with the action in the store channel.' },
      { id: 'network-explain-figures', label: 'Show the evidence', kind: 'secondary', result: 'The diagnosis links a 6.4% sales decline to delivery orders down 19%, 84 paused minutes and a rating change from 4.6 to 4.4. In-store transactions are flat. Check the original records before choosing a response.' },
    ],
    outcome: 'The manager sees the pattern and the store gets a useful next step.',
  },
];

export const zoneDetails = {
  grill: {
    title: 'At the grill',
    description: 'Bring prep reminders and food safety workflow status to the people doing the shift. Keep the approved procedure and original record in their source system.',
    channel: '#store-bankstown',
    systems: ['Food safety app', 'Store Hub', 'Approved workflows'],
  },
  counter: {
    title: 'At the counter',
    description: 'See the queue, collection and delivery signals together. Give the shift leader one clear decision, with an owner and a follow-up.',
    channel: '#store-bankstown',
    systems: ['Fingermark', 'POS / sales', 'Delivery platforms'],
  },
  stock: {
    title: 'In the stockroom',
    description: 'Connect availability checks, supply questions and delivery status. Keep the store and support team working from the same update.',
    channel: '#store-support',
    systems: ['Stock workflow', 'Uber Eats', 'Supply team'],
  },
  crew: {
    title: 'With the crew',
    description: 'Run approved cover requests and find the right training links. Managers handle approvals in the workforce app, which remains the home of the roster.',
    channel: '#store-bankstown',
    systems: ['Workforce app', 'Employment Hero', 'Store Hub'],
  },
  dining: {
    title: 'On the floor',
    description: 'Turn guest feedback into a clear follow-up and finish the shift with a useful handover. Open issues keep their owner until the job is done.',
    channel: '#store-bankstown',
    systems: ['Tattle', 'Guest feedback', 'Closing workflow'],
  },
  roof: {
    title: 'Across the network',
    description: 'Give area managers and leaders a clear view of the store network, with concise briefings, approved diagnostics and actions attached to the right store.',
    channel: '#am-southwest',
    systems: ['Snowflake', 'Approved diagnostics app', 'Weekly store pack'],
  },
};
