// Fictional examples informed by the supplied customer strategy and frontline decks.
// These are proposed demo workflows, not live feeds or operational records.
export const operationCases = [
  {
    id: 'complaints',
    number: 1,
    title: 'Spot a pattern in guest feedback',
    stage: 'rush',
    role: 'manager',
    source: 'Tattle · Google reviews · Uber Eats',
    trigger: 'Three or more complaints in the same category arrive within two hours.',
    evidence: [
      { label: 'Feedback pattern', value: 'Three missing-item reports' },
      { label: 'Review window', value: 'The past two hours' },
      { label: 'Suggested focus', value: 'Packing and order checks' },
    ],
    playbook: [
      'Bring the related reports into one store-channel alert.',
      'Assign the shift leader to check packing and order handover.',
      'Record the response and keep the original reports linked to the action.',
    ],
    actionLabel: 'Assign the packing check',
    outcome: 'The packing check has an owner in {store}. The related guest reports and follow-up stay with the action.',
  },
  {
    id: 'drive-thru',
    number: 2,
    title: 'Get the drive-thru moving',
    stage: 'rush',
    role: 'manager',
    source: 'Fingermark · store baseline',
    trigger: 'The rolling 30-minute drive-thru pace moves above the store’s usual range.',
    evidence: [
      { label: 'Current ticket time', value: '5:48' },
      { label: 'Store target', value: '4:10' },
      { label: 'Same window last week', value: '4:05' },
      { label: 'Car count', value: '22% above a normal Tuesday' },
    ],
    playbook: [
      'Compare the current window with this store’s baseline and last week.',
      'Give the shift leader ownership of the alert and review the suggested response.',
      'Open the second window, move a packer to assembly and check the next window. Escalate if the issue remains open.',
    ],
    actionLabel: 'Assign the rush playbook',
    outcome: 'The rush playbook is assigned in {store}. The owner will check the next trading window and escalate if the queue still needs help.',
  },
  {
    id: 'delivery',
    number: 3,
    title: 'Catch a paused delivery feed',
    stage: 'supply',
    role: 'manager',
    source: 'Uber Eats · trading hours · store sales',
    trigger: 'Uber Eats is offline or paused while the store is trading.',
    evidence: [
      { label: 'Delivery status', value: 'Paused for 12 minutes' },
      { label: 'Readiness check', value: 'Stock and packing bench' },
      { label: 'Estimated hourly exposure', value: 'A$1,134: 42 orders × A$27 average order' },
    ],
    playbook: [
      'Show the pause, its duration and the estimated hourly revenue impact together.',
      'Ask the store manager to confirm stock and kitchen readiness before resuming.',
      'Keep the manager’s decision with the incident and escalate to the area manager if it remains unresolved.',
    ],
    actionLabel: 'Assign the availability check',
    outcome: 'The delivery availability check is assigned in {store}. The manager owns the readiness decision, with an escalation path if the delivery pause remains open.',
  },
  {
    id: 'refunds',
    number: 4,
    title: 'Find the cause of order errors',
    stage: 'rush',
    role: 'manager',
    source: 'Delivery refunds · order errors',
    trigger: 'Refunds or order errors spike in the trailing two-hour window.',
    evidence: [
      { label: 'Refund rate', value: '7.1% against a 2.4% baseline' },
      { label: 'Large Chicken Pack', value: '4 missing-item reports' },
      { label: 'Garlic Sauce Tub', value: '3 missing-item reports' },
      { label: 'Review window', value: 'The past two hours' },
    ],
    playbook: [
      'Group the errors and show the items with the most issues.',
      'Assign a packing check focused on those items.',
      'Record the change and compare the next review window before closing the action.',
    ],
    actionLabel: 'Assign an order accuracy check',
    outcome: 'The order accuracy check is assigned in {store}. The owner can trace the error pattern to the packing response and next review.',
  },
  {
    id: 'sales',
    number: 5,
    title: 'Act on today’s trading pace',
    stage: 'supply',
    role: 'manager',
    source: 'POS · forecast · last year’s trading',
    trigger: 'The late-lunch check shows trading behind the forecast or the comparable day last year.',
    evidence: [
      { label: 'Trading checkpoint', value: '2 pm, earlier in the trading day' },
      { label: 'Sales so far', value: 'A$6,200' },
      { label: 'Forecast at this point', value: 'A$7,400; pace is 16.2% behind' },
      { label: 'Comparable day last year', value: 'A$6,900 at the same checkpoint' },
    ],
    playbook: [
      'Compare the day so far with the store forecast and last year’s comparable day.',
      'Check the channel mix and availability signals before choosing a response.',
      'Assign one useful action for the remaining trading period and set a follow-up.',
    ],
    actionLabel: 'Assign today’s trading focus',
    outcome: 'A same-day trading focus is assigned in {store}. The forecast comparison, owner and follow-up stay together in the store channel.',
  },
  {
    id: 'diagnostics',
    number: 6,
    title: 'Ask what is behind the numbers',
    stage: 'network',
    role: 'manager',
    source: 'Snowflake · approved Claude diagnostics app',
    trigger: 'A manager asks why a store is down and needs the evidence behind the change.',
    evidence: [
      { label: 'Net sales', value: 'Down 6.4% week on week' },
      { label: 'Uber Eats orders', value: 'Down 19%; in-store transactions flat' },
      { label: 'Saturday availability', value: '84 minutes paused' },
      { label: 'Guest rating', value: '4.6 to 4.4' },
    ],
    playbook: [
      'Invoke the approved diagnostics app in a channel the manager can access.',
      'Read the comparison of channel mix, traffic, spend, complaints and drive-thru signals.',
      'Inspect the evidence, then assign a store action. The pattern suggests where to investigate; it does not prove a cause.',
    ],
    actionLabel: 'Assign the diagnostic follow-up',
    outcome: 'The diagnostic follow-up is assigned in {store}, with the evidence attached. The manager owns the decision and can check the original records.',
  },
  {
    id: 'weekly-pack',
    number: 7,
    title: 'Start Monday with a clear store pack',
    stage: 'network',
    role: 'manager',
    source: 'Weekly scorecards · outstanding store actions',
    trigger: 'The area manager’s store pack arrives at 7 am on Monday.',
    evidence: [
      { label: 'Delivery time', value: 'Monday, 7 am' },
      { label: 'Priority 1: drive-thru', value: 'Ticket time 5:48 vs 4:10' },
      { label: 'Priority 2: order accuracy', value: 'Refund rate 7.1% vs 2.4%' },
      { label: 'Priority 3: availability', value: '84 paused delivery minutes on Saturday' },
      { label: 'Continuity', value: 'Unfinished actions carried forward' },
    ],
    playbook: [
      'Read the scorecard and the three weakest metrics for each store.',
      'Review last week’s unfinished actions before adding more work.',
      'Give each store a clear focus and owner in its store channel.',
    ],
    actionLabel: 'Assign the weekly store focus',
    outcome: 'The weekly focus is assigned in {store}. The store scorecard, three priority metrics and outstanding follow-ups remain easy to find.',
  },
  {
    id: 'leaderboard',
    number: 8,
    title: 'Turn a ranking change into support',
    stage: 'network',
    role: 'manager',
    source: 'Store leaderboard · metric playbooks',
    trigger: 'A store drops ten or more places, or stays in the bottom five for two weeks.',
    evidence: [
      { label: 'Ranking change', value: '18th to 30th: down 12 places' },
      { label: 'Trigger', value: 'A drop of 10 or more places' },
      { label: 'Driving metric', value: 'Order accuracy; refund rate 7.1%' },
      { label: 'Matching response', value: 'Packing accuracy playbook' },
    ],
    playbook: [
      'Name the metric behind the ranking change so the alert explains what needs attention.',
      'Give the store manager the relevant playbook and an area-manager contact.',
      'Agree on an action and review the next scorecard together.',
    ],
    actionLabel: 'Assign the improvement playbook',
    outcome: 'The improvement playbook is assigned in {store}. The manager can see the metric behind the ranking change and the next review.',
  },
  {
    id: 'follow-up',
    number: 9,
    title: 'Keep an unresolved complaint moving',
    stage: 'close',
    role: 'manager',
    source: 'Guest complaint workflow · action history',
    trigger: 'A complaint action is still open after 48 hours.',
    evidence: [
      { label: 'Open action', value: 'Guest complaint awaiting follow-up' },
      { label: 'Reminder point', value: '48 hours after the action was opened' },
      { label: 'Escalation path', value: 'Store manager, then area manager' },
    ],
    playbook: [
      'Keep the complaint, owner and next step together from the first response.',
      'Send the store manager a reminder after 48 hours.',
      'If the action remains unresolved, escalate to the area manager with its history attached.',
    ],
    actionLabel: 'Send the 48-hour reminder',
    outcome: 'The 48-hour reminder is recorded for {store}. The complaint keeps its owner and history, ready for area-manager escalation if it remains unresolved.',
  },
  {
    id: 'review',
    number: 10,
    title: 'Give every guest response a human check',
    stage: 'close',
    role: 'manager',
    source: 'Google reviews · Tattle · response workflow',
    trigger: 'A guest review needs a response and a draft is ready for the manager.',
    evidence: [
      { label: 'Review theme', value: 'A missing item in a delivery order' },
      { label: 'Draft status', value: 'Awaiting store-manager review' },
      { label: 'Final decision', value: 'Edit and approve before the response' },
    ],
    playbook: [
      'Read the review and a proposed response alongside the original record.',
      'Edit the draft so it is clear, helpful and appropriate to the guest’s experience.',
      'Have the manager approve the response. Keep the approved response with the review.',
    ],
    actionLabel: 'Review the response draft',
    outcome: 'The guest response for {store} has been reviewed and approved. The approved wording and manager decision stay with the review.',
  },
];

// The reference slide has eight headings. Huddles and clips, and canvases and
// lists, are separate experiences here so all ten capabilities can be explored.
export const frontlineFeatures = [
  {
    id: 'access',
    title: 'Email-free access',
    stage: 'opening',
    description: 'Sign in with your employee ID and a multi-factor check. Crew do not need a corporate email address.',
  },
  {
    id: 'channels',
    title: '10-channel focus',
    stage: 'opening',
    description: 'Open a curated set of up to ten assigned channels. The crew can read and post in their channels; admins manage the channel set.',
  },
  {
    id: 'clips',
    title: 'Shift briefing clips',
    stage: 'opening',
    description: 'Play a short briefing from the shift leader and catch the key points before service.',
  },
  {
    id: 'canvas',
    title: 'Read the Store Hub canvas',
    stage: 'opening',
    description: 'Find the promotion, shift contacts and current procedure links in a view-only canvas maintained by the business.',
  },
  {
    id: 'lists',
    title: 'See the shift task list',
    stage: 'opening',
    description: 'Read the team’s tasks, owners and status in a view-only list. Record your checks through the approved workflow.',
  },
  {
    id: 'shifts',
    title: 'Manage your shift',
    stage: 'opening',
    description: 'View your schedule, clock in and request an open shift through an integrated workforce app. Managers approve roster changes.',
  },
  {
    id: 'workflows',
    title: 'Run one-tap workflows',
    stage: 'prep',
    description: 'Run a workflow the business has already approved to record a check, log an issue or ask for help.',
  },
  {
    id: 'huddles',
    title: 'Join a huddle',
    stage: 'rush',
    description: 'Join a voice huddle with the shift leader to coordinate the response while the team stays close to the floor.',
  },
  {
    id: 'agents',
    title: 'Ask an approved in-channel agent',
    stage: 'people',
    description: 'Invoke an approved app or agent in an assigned channel to find a procedure or the right workflow. The business manages its access and setup.',
  },
  {
    id: 'governance',
    title: 'Keep store work governed and secure',
    stage: 'close',
    description: 'Explore the crew’s focused workspace with external DMs and Slack Connect restricted. Managers keep approvals and the wider store view.',
  },
];
